spring:
  profiles:
    active: multi
  data:
    redis:
      password: 123456
      host: 192.168.110.164
      port: 6379
      lettuce:
        pool:
          max-active: 500 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 500 # 连接池中的最大空闲连接
          min-idle: 20 # 连接池中的最小空闲连接
          max-wait: 60000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  jta:
    atomikos:
      datasource:
        max-pool-size: 100
        min-pool-size: 20
logging:
  level:
    root: info